// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(SuitSupplyDbContext))]
    [Migration("20191116212948_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.ProductCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ProductCatalogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Suit_Black",
                            Name = "Black Suit",
                            Photo = "http://pngimg.com/uploads/suit/suit_PNG8134.png",
                            Price = 140m
                        },
                        new
                        {
                            Id = 2,
                            Code = "Blue_Black",
                            Name = "Blue Suit",
                            Photo = "http://pngimg.com/uploads/suit/suit_PNG8121.png",
                            Price = 150m
                        },
                        new
                        {
                            Id = 3,
                            Code = "Grey_Black",
                            Name = "Grey Suit",
                            Photo = "http://pngimg.com/uploads/suit/suit_PNG8133.png",
                            Price = 160m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
